# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24)),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10)),
                ('info', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
